[package]
name = "sorting-comparison"
version = "0.1.0"
edition = "2021"

[lib]
name = "sorting_comparison"
crate-type = ["cdylib"]

[dependencies]
rand = "0.8.5"
pyo3 = { version = "0.22.4", features = ["extension-module"] }
