[package]
name = "sorting-comparison"
version = "0.1.0"
edition = "2021"

[lib]
name = "sorting_comparison"
path = "src/lib.rs"

[[bin]]
name = "bogo_sort"
path = "src/lib.rs"

[dependencies]
rand = "0.8.5"
