[project]
name = "sorting-comparison"
description = "Comparison of Python merge sort and Rust bogo sort"
readme = "README.md"
requires-python = ">=3.12"
dynamic = ["version"]
dependencies = [
    "matplotlib>=3.7.5",
]
